-- PostgreSQL Extensions
-- Generated by nself build

\c nself

-- Enable UUID support
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Enable cryptographic functions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Enable JSONB operators (commented out - requires Python runtime)
-- CREATE EXTENSION IF NOT EXISTS "jsonb_plpython3u" CASCADE;
