-- 05-np-plugins-seed.sql
-- Generated by `nself build`. DO NOT EDIT.
-- Idempotent: ON CONFLICT (name) DO NOTHING. Safe to re-run.
-- Seeds one np_plugins row per plugin currently installed on disk.

INSERT INTO np_plugins (name, tier) VALUES ('backup', 'pro') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('cron', 'pro') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('devices', 'free') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('epg', 'free') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('file-processing', 'free') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('jobs', 'free') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('media-processing', 'free') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('metadata-enrichment', 'free') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('notifications', 'free') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('notify', 'pro') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('recording', 'free') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('retro-gaming', 'free') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('rom-discovery', 'free') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('sports', 'free') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('stream-gateway', 'free') ON CONFLICT (name) DO NOTHING;
INSERT INTO np_plugins (name, tier) VALUES ('workflows', 'free') ON CONFLICT (name) DO NOTHING;
