-- Down migration paired with 002_add_task_approval_system.sql (P99 1.11 T08 autogenerated)
-- Rollback for Task Approval System.
-- Idempotent (IF EXISTS guards). Order: triggers/functions → policies → ALTER TABLE drops →
-- new tables. Restoring the prior app_todos RLS policies is intentionally NOT attempted
-- (review original init.sql to recreate those if rolling back further).

-- ---------------------------------------------------------------------------
-- Triggers + functions
-- ---------------------------------------------------------------------------
DROP TRIGGER IF EXISTS track_completion ON public.app_todos;
DROP FUNCTION IF EXISTS public.track_todo_completion();

DROP TRIGGER IF EXISTS on_list_created_add_owner ON public.app_lists;
DROP FUNCTION IF EXISTS public.handle_new_list_owner();

DROP FUNCTION IF EXISTS public.approve_task(UUID, UUID);
DROP FUNCTION IF EXISTS public.reject_task(UUID, UUID, TEXT);
DROP FUNCTION IF EXISTS public.can_approve_tasks(UUID, UUID);
DROP FUNCTION IF EXISTS public.get_user_list_role(UUID, UUID);

-- ---------------------------------------------------------------------------
-- Policies on app_todos created by this migration
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "Owners and creators can delete todos" ON public.app_todos;
DROP POLICY IF EXISTS "Members can update todos" ON public.app_todos;
DROP POLICY IF EXISTS "Members can create todos" ON public.app_todos;
DROP POLICY IF EXISTS "Users can view accessible todos" ON public.app_todos;

-- NOTE: prior init.sql policies (Users can view their own todos, etc.) are
-- intentionally NOT recreated here. Re-run init.sql RLS section if needed.

-- ---------------------------------------------------------------------------
-- Policies on app_list_members
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "Owners can remove members" ON public.app_list_members;
DROP POLICY IF EXISTS "Owners can manage members" ON public.app_list_members;
DROP POLICY IF EXISTS "Owners and admins can add members" ON public.app_list_members;
DROP POLICY IF EXISTS "Users can view list members" ON public.app_list_members;

-- ---------------------------------------------------------------------------
-- app_todos columns added by this migration
-- ---------------------------------------------------------------------------
ALTER TABLE public.app_todos DROP COLUMN IF EXISTS completed_at;
ALTER TABLE public.app_todos DROP COLUMN IF EXISTS rejection_reason;
ALTER TABLE public.app_todos DROP COLUMN IF EXISTS rejected_at;
ALTER TABLE public.app_todos DROP COLUMN IF EXISTS rejected_by;
ALTER TABLE public.app_todos DROP COLUMN IF EXISTS completion_notes;
ALTER TABLE public.app_todos DROP COLUMN IF EXISTS completion_photo_url;
ALTER TABLE public.app_todos DROP COLUMN IF EXISTS approved_at;
ALTER TABLE public.app_todos DROP COLUMN IF EXISTS approved_by;
ALTER TABLE public.app_todos DROP COLUMN IF EXISTS approved;
ALTER TABLE public.app_todos DROP COLUMN IF EXISTS completed_by;
ALTER TABLE public.app_todos DROP COLUMN IF EXISTS requires_photo;
ALTER TABLE public.app_todos DROP COLUMN IF EXISTS requires_approval;

-- Indexes for the dropped columns are dropped automatically with the columns.

-- ---------------------------------------------------------------------------
-- New table: app_list_members
-- ---------------------------------------------------------------------------
DROP TRIGGER IF EXISTS set_app_list_members_updated_at ON public.app_list_members;
DROP INDEX IF EXISTS idx_app_list_members_role;
DROP INDEX IF EXISTS idx_app_list_members_user_id;
DROP INDEX IF EXISTS idx_app_list_members_list_id;
DROP TABLE IF EXISTS public.app_list_members;
