-- Down migration paired with 004_ntasks_rls.sql (P99 1.11 T08 autogenerated)
-- Rollback for the RLS-enable migration.
-- This migration only enabled RLS + (re)created app_user_preferences policies.
-- Disabling RLS on tables that pre-existed this migration would weaken the
-- ambient security posture. We therefore:
--   1. Drop only the policies this migration created on app_user_preferences
--      (already dropped by 003 down, but kept here for symmetry / re-run safety).
--   2. Do NOT disable RLS on the tables — the original init.sql migration enabled
--      RLS on most of them, and turning it off here would silently expose data.
-- Idempotent (IF EXISTS guards).

DROP POLICY IF EXISTS "Users can delete their own preferences" ON public.app_user_preferences;
DROP POLICY IF EXISTS "Users can update their own preferences" ON public.app_user_preferences;
DROP POLICY IF EXISTS "Users can insert their own preferences" ON public.app_user_preferences;
DROP POLICY IF EXISTS "Users can view their own preferences" ON public.app_user_preferences;

-- NOTE: ALTER TABLE ... DISABLE ROW LEVEL SECURITY is intentionally NOT issued
-- for any table here. Re-enabling RLS later would be silent — flipping it off
-- now is a security regression. To fully invert this migration, the operator
-- must explicitly run DISABLE ROW LEVEL SECURITY per table after auditing.
