-- Down migration paired with 005_presence_cron.sql (P99 1.11 T08 autogenerated)
-- Rollback for stale-presence pg_cron scheduled job.
-- Idempotent: cron.unschedule may fail if the job is already gone, so wrap in DO block.
-- Does NOT drop pg_cron extension or the index (both predate this migration in init.sql).

DO $$
BEGIN
  -- pg_cron may not be installed when rolling back on a fresh DB; guard the call.
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.unschedule('ntasks-cleanup-stale-presence')
    WHERE EXISTS (
      SELECT 1 FROM cron.job WHERE jobname = 'ntasks-cleanup-stale-presence'
    );
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;  -- cron.job table absent
  WHEN undefined_function THEN NULL;  -- cron.unschedule absent
END;
$$;

-- NOTE: idx_app_list_presence_last_seen + pg_cron extension are intentionally
-- NOT dropped here (predate this migration; widely used by other features).
