-- Down migration paired with 006_list_groups.sql (P99 1.11 T08 autogenerated)
-- Rollback for List Groups feature.
-- Idempotent (IF EXISTS guards). Drops trigger + function before table; drops
-- group_id column from app_lists; drops the app_list_groups table last.

-- Trigger + function
DROP TRIGGER IF EXISTS set_app_list_groups_updated_at ON public.app_list_groups;
DROP FUNCTION IF EXISTS update_app_list_groups_updated_at();

-- RLS policies on app_list_groups
DROP POLICY IF EXISTS "Users can delete their own groups" ON public.app_list_groups;
DROP POLICY IF EXISTS "Users can update their own groups" ON public.app_list_groups;
DROP POLICY IF EXISTS "Users can create their own groups" ON public.app_list_groups;
DROP POLICY IF EXISTS "Users can view their own groups" ON public.app_list_groups;

-- Drop FK column on app_lists (does not affect existing rows beyond losing the FK reference)
ALTER TABLE public.app_lists DROP COLUMN IF EXISTS group_id;

-- Drop the table
DROP TABLE IF EXISTS public.app_list_groups;
