-- Down migration paired with 008_recurring_task_cron.sql (P99 1.11 T08 autogenerated)
-- Rollback for server-side recurring-task instance creation (T-2423).
-- Idempotent: cron.unschedule guarded; pg_cron extension NOT dropped (predates).

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.unschedule('ntask-create-recurring-instances')
    WHERE EXISTS (
      SELECT 1 FROM cron.job WHERE jobname = 'ntask-create-recurring-instances'
    );
  END IF;
EXCEPTION
  WHEN undefined_table THEN NULL;
  WHEN undefined_function THEN NULL;
END;
$$;

DROP FUNCTION IF EXISTS public.create_recurring_instances();

-- NOTE: pg_cron extension is intentionally NOT dropped here.
